// Generated by axtp-gen. Do not edit manually.
#pragma once
#include <cstddef>
#include <cstdint>

#include "axtp_ids_generated.h"

namespace axtp {

struct LegacyStatusMapping {
    std::uint16_t legacy_status;
    ErrorCode axtp_error;
    const char* axtp_error_name;
};

struct LegacyCmdMapping {
    const char* legacy_protocol;
    std::uint32_t legacy_cmd_value;
    std::uint16_t axtp_method_id;
    const char* axtp_method_name;
    const LegacyStatusMapping* status_mappings;
    std::size_t status_mapping_count;
};

inline constexpr LegacyStatusMapping kLegacyStatusMappings0[] = {
    { 0x00, ErrorCode::Success, "SUCCESS" },
};

inline constexpr LegacyCmdMapping kLegacyMappings[] = {
    { "axdp_hid", 0x00000042, 0x0502, "display.setBrightness", kLegacyStatusMappings0, 1 },
};

inline constexpr std::size_t kLegacyMappingCount = 1;

} // namespace axtp
